name: het_env
channels:
  - pytorch
  - nvidia
dependencies:
  - matplotlib
  - scikit-learn
  - seaborn
  - swig
  - ffmpeg
  - tqdm
  - pip
  - pip:
      - neat-python
      - wandb
      - graphviz
      - torch
      - torchvision
      - torchaudio
      - "gymnasium[all]"
      - git+https://github.com/DLR-RM/stable-baselines3.git@8f0b488
      - imecilabt-gpulab-cli